
###

# @name chapters
GET http://localhost:7071/api/chapters?s=1-2-3-4&l=fr&w=150

###


# @name features
GET http://localhost:7071/api/features?c=1&l=en

###

# @name health
GET http://localhost:7071/api/health

###
